name: news_reading_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.10.0
  firebase_database: ^11.2.0
  firebase_messaging: ^15.2.0
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.15.3
  flutter_widget_from_html_core: ^0.15.2
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  html: ^0.15.5
  http: ^1.2.2
  intl: ^0.20.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  share_plus: ^10.1.3
  simple_fontellico_progress_dialog: ^0.3.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
