name: news_reading_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
 
  flutter:
    sdk: flutter
  # firebase_messaging: ^15.2.0
  google_sign_in: ^6.2.2
  # google_sign_in_android: ^6.1.34
  url_launcher: ^6.3.1
  # flutter_web_auth_2: ^4.1.0
  flutter_web_auth: ^0.6.0
  
  provider: ^6.1.2

   # Thời tiết
  lottie: ^3.2.0
  geolocator: ^13.0.2
  http: ^1.2.2
  geocoding: ^3.0.0
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Default.jpg
    - assets/

