name: news_reading_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.10.0
  firebase_database: ^11.2.0
  firebase_messaging: ^15.2.0
  flutter:
    sdk: flutter
  http:
  flutter_inappwebview:
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  share_plus: ^10.1.3
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    # - assets/images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
        # Nếu bạn muốn thêm font khác:
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic