// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNuYwazO_lvvpQMmST1XEVjGTQbFDA-g',
    appId: '1:289978268874:web:7a7b44b0c569df5a488833',
    messagingSenderId: '289978268874',
    projectId: 'flutter-firebase-60516',
    authDomain: 'flutter-firebase-60516.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-60516-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-60516.firebasestorage.app',
    measurementId: 'G-EM5GS4EBTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5kJCcyMEyCnIVQ02IWLIuZRJ5m3SF_ps',
    appId: '1:289978268874:android:73543573af9a8d26488833',
    messagingSenderId: '289978268874',
    projectId: 'flutter-firebase-60516',
    databaseURL: 'https://flutter-firebase-60516-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-60516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb1M_3vwdtAChqfHwcNFOmaPAyy4a3tB8',
    appId: '1:289978268874:ios:4343d13e471e5f19488833',
    messagingSenderId: '289978268874',
    projectId: 'flutter-firebase-60516',
    databaseURL: 'https://flutter-firebase-60516-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-60516.firebasestorage.app',
    iosBundleId: 'com.example.newsReadingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb1M_3vwdtAChqfHwcNFOmaPAyy4a3tB8',
    appId: '1:289978268874:ios:4343d13e471e5f19488833',
    messagingSenderId: '289978268874',
    projectId: 'flutter-firebase-60516',
    databaseURL: 'https://flutter-firebase-60516-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-60516.firebasestorage.app',
    iosBundleId: 'com.example.newsReadingApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYNuYwazO_lvvpQMmST1XEVjGTQbFDA-g',
    appId: '1:289978268874:web:2a9a4c934289fba8488833',
    messagingSenderId: '289978268874',
    projectId: 'flutter-firebase-60516',
    authDomain: 'flutter-firebase-60516.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-60516-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-60516.firebasestorage.app',
    measurementId: 'G-0S3ZCPQY6L',
  );
}
